version: '3.9'
services:
  front:
    container_name: 'um_front'
    build:
      context: './user-management-frontend'
    env_file:
      - '.env'
    ports:
      - '3000:3000'
    volumes:
      - './user-management-frontend:/app'
      - '/app/node_modules'
